version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_CDN_URL=${NEXT_PUBLIC_CDN_URL}
        - KINDE_CLIENT_ID=${KINDE_CLIENT_ID}
        - KINDE_CLIENT_SECRET=${KINDE_CLIENT_SECRET}
        - KINDE_ISSUER_URL=${KINDE_ISSUER_URL}
        - KINDE_SITE_URL=${KINDE_SITE_URL}
        - KINDE_POST_LOGOUT_REDIRECT_URL=${KINDE_POST_LOGOUT_REDIRECT_URL}
        - KINDE_POST_LOGIN_REDIRECT_URL=${KINDE_POST_LOGIN_REDIRECT_URL}
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/advent_calendar?schema=public"
      CDN_URL: ${CDN_URL}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      CLOUDFRONT_KEY_PAIR_ID: ${CLOUDFRONT_KEY_PAIR_ID}
      CLOUDFRONT_PRIVATE_KEY: ${CLOUDFRONT_PRIVATE_KEY}
      KINDE_CLIENT_ID: ${KINDE_CLIENT_ID}
      KINDE_CLIENT_SECRET: ${KINDE_CLIENT_SECRET}
      KINDE_ISSUER_URL: ${KINDE_ISSUER_URL}
      KINDE_SITE_URL: ${KINDE_SITE_URL}
      KINDE_POST_LOGOUT_REDIRECT_URL: ${KINDE_POST_LOGOUT_REDIRECT_URL}
      KINDE_POST_LOGIN_REDIRECT_URL: ${KINDE_POST_LOGIN_REDIRECT_URL}
      KINDE_M2M_CLIENT_ID: ${KINDE_M2M_CLIENT_ID}
      KINDE_M2M_CLIENT_SECRET: ${KINDE_M2M_CLIENT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=advent_calendar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d advent_calendar"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge